/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.5
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "cudaGen"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "cudaGen"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * dir_arg;	/**< @brief Output directory. If it already exists, a new one will be created adding YYYY.MM.DD---HHhMM.SSs (default='OutDir').  */
  char * dir_orig;	/**< @brief Output directory. If it already exists, a new one will be created adding YYYY.MM.DD---HHhMM.SSs original value given at command line.  */
  const char *dir_help; /**< @brief Output directory. If it already exists, a new one will be created adding YYYY.MM.DD---HHhMM.SSs help description.  */
  const char *about_help; /**< @brief the about info (authors, date, etc.) help description.  */
  int regular_code_flag;	/**< @brief Generate simple C template without CUDA (default=off).  */
  const char *regular_code_help; /**< @brief Generate simple C template without CUDA help description.  */
  int Force_flag;	/**< @brief force destination directory (default=off).  */
  const char *Force_help; /**< @brief force destination directory help description.  */
  int measure_flag;	/**< @brief kernel measure GPU execution time (default=off).  */
  const char *measure_help; /**< @brief kernel measure GPU execution time help description.  */
  int* blocks_arg;	/**< @brief Kernel geometry in blocks.  */
  char ** blocks_orig;	/**< @brief Kernel geometry in blocks original value given at command line.  */
  unsigned int blocks_min; /**< @brief Kernel geometry in blocks's minimum occurreces */
  unsigned int blocks_max; /**< @brief Kernel geometry in blocks's maximum occurreces */
  const char *blocks_help; /**< @brief Kernel geometry in blocks help description.  */
  int* threads_arg;	/**< @brief threads geometry.  */
  char ** threads_orig;	/**< @brief threads geometry original value given at command line.  */
  unsigned int threads_min; /**< @brief threads geometry's minimum occurreces */
  unsigned int threads_max; /**< @brief threads geometry's maximum occurreces */
  const char *threads_help; /**< @brief threads geometry help description.  */
  char * kernel_arg;	/**< @brief Kernel name (default='kernel').  */
  char * kernel_orig;	/**< @brief Kernel name original value given at command line.  */
  const char *kernel_help; /**< @brief Kernel name help description.  */
  char * proto_arg;	/**< @brief kernel proto.  */
  char * proto_orig;	/**< @brief kernel proto original value given at command line.  */
  const char *proto_help; /**< @brief kernel proto help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int dir_given ;	/**< @brief Whether dir was given.  */
  unsigned int about_given ;	/**< @brief Whether about was given.  */
  unsigned int regular_code_given ;	/**< @brief Whether regular-code was given.  */
  unsigned int Force_given ;	/**< @brief Whether Force was given.  */
  unsigned int measure_given ;	/**< @brief Whether measure was given.  */
  unsigned int blocks_given ;	/**< @brief Whether blocks was given.  */
  unsigned int threads_given ;	/**< @brief Whether threads was given.  */
  unsigned int kernel_given ;	/**< @brief Whether kernel was given.  */
  unsigned int proto_given ;	/**< @brief Whether proto was given.  */

  int what_I_want_todo_group_counter; /**< @brief Counter for group what_I_want_todo */
  int modeGeometry_mode_counter; /**< @brief Counter for mode modeGeometry */
  int modeKernel_mode_counter; /**< @brief Counter for mode modeKernel */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
